import type { IncidentRow } from './db';
import { getServiceBySlug } from './services';

function formatDuration(startIso: string | null, endIso: string | null): string {
  if (!startIso || !endIso) return 'Unknown';
  const ms = new Date(endIso).getTime() - new Date(startIso).getTime();
  if (ms < 0) return 'Unknown';
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  if (h === 0) return `${m} minute${m !== 1 ? 's' : ''}`;
  return `${h}h ${m}m`;
}

export function generatePostmortemMarkdown(incident: IncidentRow): string {
  const service = getServiceBySlug(incident.service_slug);
  const serviceName = service?.name ?? incident.service_slug;
  const duration = formatDuration(incident.started_at, incident.resolved_at);
  const startedAt = incident.started_at ? new Date(incident.started_at).toISOString() : 'Unknown';
  const resolvedAt = incident.resolved_at ? new Date(incident.resolved_at).toISOString() : 'Unresolved';

  return `# Incident Postmortem: ${incident.title}

**Service:** ${serviceName}
**Severity:** ${incident.severity}
**Incident ID:** ${incident.incident_id}
**Status:** ${incident.status}
**Duration:** ${duration}

---

## Timeline

| Time | Event |
|------|-------|
| ${startedAt} | Incident detected / reported |
${incident.resolved_at ? `| ${resolvedAt} | Incident resolved |` : `| — | Not yet resolved |`}

<!-- Add intermediate timeline entries here (e.g., when identified, when fix deployed) -->

---

## Impact

- **Affected service:** ${serviceName}
- **Severity:** ${incident.severity}
- **Duration:** ${duration}
- **User impact:** <!-- Describe which features/APIs were affected and estimated user count -->

---

## Root Cause Analysis

<!-- Describe what caused the incident. Be specific and honest. -->

**What happened:**
> ${incident.description ?? '*(No description recorded — add details here)*'}

**Why it happened:**
> <!-- Describe the underlying cause, not just the symptom -->

**Why it wasn't caught earlier:**
> <!-- What monitoring, tests, or processes failed to detect this sooner? -->

---

## Contributing Factors

- [ ] <!-- Factor 1 -->
- [ ] <!-- Factor 2 -->
- [ ] <!-- Factor 3 -->

---

## Action Items

| Action | Owner | Due Date | Status |
|--------|-------|----------|--------|
| <!-- Describe action item --> | <!-- Team/person --> | <!-- Date --> | Open |
| <!-- Add monitoring/alerting improvements --> | <!-- Team/person --> | <!-- Date --> | Open |

---

## Lessons Learned

<!-- What went well? What could be improved? -->

**What went well:**
- <!-- e.g., fast detection, clear communication -->

**What could be improved:**
- <!-- e.g., slow escalation, manual steps -->

---

*Generated by Outage Map at ${new Date().toISOString()}*
`;
}
